# Generated by Django 2.2.12 on 2020-04-27 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grandcategory',
            name='icon',
            field=models.CharField(default=1, max_length=50, verbose_name='アイコン'),
            preserve_default=False,
        ),
    ]
