# Generated by Django 2.2.12 on 2020-05-11 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20200511_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='grandCategory',
        ),
        migrations.RemoveField(
            model_name='post',
            name='parentCategory',
        ),
    ]
