# Generated by Django 2.2.12 on 2020-04-15 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_auto_20200415_1316'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
