# Generated by Django 2.2.12 on 2020-04-16 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_delete_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Camera',
            new_name='Category',
        ),
    ]
